package com.camel.cxf.server;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-06-26T17:47:01.515+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "CamelCXFServiceImplService",
                  wsdlLocation = "D:/IDEASyswinWorkSpace/framework-camel/wsdl/queryService.wsdl",
                  targetNamespace = "http://server.cxf.camel.com/")
public class CamelCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.cxf.camel.com/", "CamelCXFServiceImplService");
    public final static QName CamelCXFServiceImplPort = new QName("http://server.cxf.camel.com/", "CamelCXFServiceImplPort");
    static {
        URL url = CamelCXFServiceImplService.class.getResource("D:/IDEASyswinWorkSpace/framework-camel/wsdl/queryService.wsdl");
        if (url == null) {
            url = CamelCXFServiceImplService.class.getClassLoader().getResource("D:/IDEASyswinWorkSpace/framework-camel/wsdl/queryService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(CamelCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "D:/IDEASyswinWorkSpace/framework-camel/wsdl/queryService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CamelCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CamelCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CamelCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CamelCXFServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CamelCXFServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CamelCXFServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CamelCXFServiceInter
     */
    @WebEndpoint(name = "CamelCXFServiceImplPort")
    public CamelCXFServiceInter getCamelCXFServiceImplPort() {
        return super.getPort(CamelCXFServiceImplPort, CamelCXFServiceInter.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CamelCXFServiceInter
     */
    @WebEndpoint(name = "CamelCXFServiceImplPort")
    public CamelCXFServiceInter getCamelCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CamelCXFServiceImplPort, CamelCXFServiceInter.class, features);
    }

}
